export const projects = [{
        id: 'ecommerce-management-system',
        title: 'E-Commerce & Management System',
        img1_path: '../images/ecom_home_page.png',
        img2_path: '../images/ecom_dashboard_page.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        tech_used: 'PHP . jQuery . MySQL . AWS',
        source_code: 'https://github.com/JChirindza',
        web_site: '',
    },
    {
        id: 'careers-recruiment-system',
        title: 'Careers & Recruitment System',
        img1_path: '../images/careers_jobs_filters_page.png',
        img2_path: '../images/ecom_home_page.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        tech_used: 'PHP . jQuery . MySQL . Heroku',
        source_code: 'https://github.com/JChirindza',
        web_site: '',
    },
    {
        id: 'point-of-sale',
        title: 'Point Of Sale & Stock Management System',
        img1_path: '../images/ecom_home_page.png',
        img2_path: '../images/ecom_home_page.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        tech_used: 'JAVA . MySQL . MVC',
        source_code: 'https://github.com/JChirindza',
        web_site: '',
    },
    {
        id: 'sbo-web-site',
        title: 'S.B.O web site - HipHop Artist',
        img1_path: '../images/sbo_web_site_home_page.png',
        img2_path: '../images/sbo_web_site_releases_page.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        tech_used: 'Html . CSS . JS . Github Pages',
        source_code: 'https://github.com/JChirindza',
        web_site: '',
    },
    {
        id: 'hulu-clone',
        title: 'Hulu 2.0 clone',
        img1_path: '../images/hulu_clone_home_page.png',
        img2_path: '',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        tech_used: 'NodeJS . NextJS . Tailwindcss . Vercel',
        source_code: 'https://github.com/JChirindza',
        web_site: '',
    },
]