export const projects = [{
        id: 'ecommerce-management-system',
        title: 'E-Commerce & Management System',
        excerpt: 'This was a project I started back in november 2017 when I first learned python...',
        body: 'In this ecommerce system We can’t get enough of our mobile apps. There were 204 billion apps downloads last year, and that number is rising in 2020.  When app stores entered the mainstream tech culture, they exposed developers to an audience of millions who were keen to adopt the innovative capabilities',
        img_main_path: '../images/ecom_home_page.png',
        tech_used: 'PHP . jQuery . MySQL . AWS',
    },
    {
        id: 'careers-recruiment-system',
        title: 'GitHub introduces dark mode and auto-merge pull request',
        excerpt: 'GitHub today announced a bunch of new features at its virtual GitHub...',
        body: 'GitHub today announced a bunch of new features at its virtual GitHub Universe conference including dark mode, auto-merge pull requests, and Enterprise Server 3.0. In the past couple of years, almost all major apps have rolled out a dark theme for its users, so why not GitHub?',
        img_main_path: '../images/ecom_home_page.png',
        tech_used: 'PHP . jQuery . MySQL . AWS',
    },
    {
        id: 'point-of-sale',
        title: 'What’s multi-cloud? And why should developers care?',
        excerpt: 'An accessible website is one that’s optimized for all people, including those with disabilities...',
        body: 'There are many things to consider when setting up a website, and accessibility is one factor that can sometimes be overlooked. An accessible website is one that’s optimized for all people, including those with impaired vision or hearing, motor difficulties, or learning disabilities',
        img_main_path: '../images/ecom_home_page.png',
        tech_used: 'JAVA . MySQL . SpringBoot',
    },
    {
        id: '1',
        title: 'Here is how to make your website more accessible',
        excerpt: 'An accessible website is one that’s optimized for all people, including those with disabilities...',
        body: 'There are many things to consider when setting up a website, and accessibility is one factor that can sometimes be overlooked. An accessible website is one that’s optimized for all people, including those with impaired vision or hearing, motor difficulties, or learning disabilities',
        img_main_path: '../images/ecom_home_page.png',
        tech_used: 'Laravel . React JS . Heroku',
    },
    {
        id: '2',
        title: 'Why open ecosystems are the future of app development',
        excerpt: 'When app stores entered the mainstream tech culture, they exposed developers to an audience of millions...',
        body: 'We can’t get enough of our mobile apps. There were 204 billion apps downloads last year, and that number is rising in 2020.  When app stores entered the mainstream tech culture, they exposed developers to an audience of millions who were keen to adopt the innovative capabilities',
        img_main_path: '../images/ecom_home_page.png',
        tech_used: 'Node JS . Next JS . Vercel',
    },
]